{% set name = "opentelemetry-instrumentation-milvus" %}
{% set version = "0.52.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_milvus-{{ version }}.tar.gz
  sha256: 02028f9ae9c34127c7abb207e373e9c0c94a3e4a2c0fdd566fe38b09e1f11474

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - opentelemetry-api >=1.28.0,<2.0.0
    - opentelemetry-semantic-conventions >=0.50b0
    - opentelemetry-instrumentation >=0.50b0
    - opentelemetry-semantic-conventions-ai >=0.4.12,<0.5
  run_constrained:
    - pymilvus >=2.4.1,<3.0.0

test:
  # pymilvus is too old on conda-forge
  # imports:
  #   - opentelemetry.instrumentation.milvus
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.traceloop.com/openllmetry
  dev_url: https://github.com/traceloop/openllmetry
  doc_url: https://www.traceloop.com/docs/openllmetry/introduction
  summary: OpenTelemetry Milvus instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
